### ISSUE TITLE
"s.getOwnerNFTs is not a function" error on NFT page

### ISSUE THREAD

**Issue by alanchiu** [omgnetwork/optimism-v2#261]
Connected my wallet to the gateway
Added Boba Punks contract
Got "s.getOwnerNFTs is not a function" error after a few seconds
<img width="933" alt="Screen Shot 2022-01-04 at 5 46 30 PM" src="https://user-images.githubusercontent.com/2431457/148148356-bdab28d3-2586-461c-8f68-d3f1e8f67655.png">

**Comment by EpicChicken** [comment]
I started getting this error today. I had the Boba Punks contract address added for a while and owned 4 NFTs. I listed one on the marketplace and started getting the "s.getOwnerNFTs is not a function" error popup multiple times per minute. All 4 NFTs were still displayed, even the one I had listed on the marketplace (and expected to no longer be displayed). 

I tried removing and re-adding the Boba Punks contract address to see if it would clear the error, but adding the contract address back doesn't work and I get the following console error:

![image](https://user-images.githubusercontent.com/91504062/149051970-a7cb5fa8-f5d8-497d-b67b-094049404a5a.png)

**Comment by CAPtheorem** [comment]
The gateway assumes that all ERC721s are `ERC721Enumerable` but that is not universally true. We can fix this by removing NFT autodiscovery from the gateway, so that each NFT must be added manually by adding the NFT contract and the `tokenID`. This would make the NFT display more robust, since it would be guaranteed to work with all ERC721 (even if they are not ERC721Enumerable)

**Comment by CAPtheorem** [comment]
fixed in new gateway
